travis:
  secure:
    BINSTAR_TOKEN: g8rnp+L046SfcCiP7KveiAJqIGEXkSRRnUjInqRtipoW3D0wBiubQHPlPbGtN7jy6IDxh4xLfDAQlI3IgvN/sUv9djjL68EXo9j9qN6E4CRev7VvQOSAxKdM8wl0d2y9m1/Qh+LsgpNHOZsFXrl15JxL8rmuqQJ/rS7Rl++NbawTrovDrYRgGBNRochth0Ag9zGXhN/Z7j3tCn1KF23omjZz1aIHeoIzJFCVGztrqs5vJKdV1+HXHcayMcGOmRdsrBPudTCdmdkETvAxfx1/o1Ms1BXo+IH02IF67PV3VDIJxOaPr6HGNM7YB1wX0r8gyGXPMPnuA/pv+mbYcviHvbMvvP5AZTVwI/JcCTB9BuJLTtsYEtHIHPKNhJWByziJ6nDHQyoacqu+QzWmQtJj7g+F6Hf87BUqaLfvIs+c+vb/gMQ4yQpHsw9dZdJBffaXMDcLwRYkd0ywxY9s8QTuKftfv00R4Sb38lgXyD7kcZs3JOZSdInWOlJm20nsq29wwyJ8lONrP2xKfN7IlUdJDZR8BVd86amNJsdkgHPqevH8lRVwzx2/uUGF3IRYHyYO9Jy8d34peegEft8ra29u/jbhxDVPhWgnXHi339/7FGs3pTPz/gNR4ZkB8+4Y87i5ad1tehG+ab7mGqD6t1KOwW8hAypXOhrfV+7oth5m6wM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
