travis:
  secure:
    BINSTAR_TOKEN: C7kiKDHtL9vbtgiKpvCwvfjpIHdaobu6M/XtkaYbV1BXa+8yA9GJtjuyjhdR+Ll+HdNUeqaM48jkaigyZ1DwI+OSU85grW9TPZ2sYUpkrpPjXuraRdVUGIVgWKiKlTeYv3F2BD+su1XPEIAi354h6NqcqdPfIDPHhD00siI5wBNYGrUA9xp7uxeMu25oDNExx8znJ7176oDuV4F374Kv10ep2wrpLFAFhi5g/I8LuyfNjYriqKTk0M0jBtr/iO7bpbXkc/z8AAPIixxmq/k7BkjiRJ1TpogFv2K1MvcIcrind93GmVTKAdjMD7mczdmK5aRmEgIMym9DhE7psPx75E/ygLEtMB483xNjeq05MMU4I4wvm5+sGmgp7WJxZZ6r4TWdTpn9APx9XcX6h9W0A0/sHPbHgP3tRAS65AT+sOlU6GjplfoBE/mr+xRZQ7KBbJMObXrjAhCfmNdVUsXZP+rK2xbgACn91080aGoQdc8FWEIgdKWuhDirtFT8fCwrYWmg0UhP3MFeBu8zilqLhq6mKclWyZpkdr/Mr0LYpmff5cBcFFj8SNSxM12yuxdls7yYPz2XVOMshUwTH5M+IF4gppawMhusy8oLZRcElu1i55zQjlMPU5nUvwwCaDnOpAGyXoDCY6BIa4uOYr64OhmSR0JwMa4TEZqfGoULxyU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
